image: Visual Studio 2017
install:
- choco install gitversion.portable -pre -y
assembly_info:
  patch: false
before_build:
- cmd: cd src
- cmd: dotnet --version
- ps: gitversion /l console /output buildserver /updateassemblyinfo
- cmd: msbuild /t:Restore
configuration: Release
build_script:
- cmd: msbuild Augurk.CSharpAnalyzer.Specifications/Augurk.CSharpAnalyzer.Specifications.csproj /t:Build /verbosity:minimal /p:Configuration=%CONFIGURATION% /p:Version=%GITVERSION_MAJORMINORPATCH% /p:InformationalVersion=%GITVERSION_INFORMATIONALVERSION%
test_script:
- cmd: vstest.console /Logger:Appveyor Augurk.CSharpAnalyzer.Specifications\bin\Release\Augurk.CSharpAnalyzer.Specifications.dll
- cmd: dotnet test Augurk.CSharpAnalyzer.UnitTest/Augurk.CSharpAnalyzer.UnitTest.csproj
after_test:
- cmd: msbuild Augurk.CSharpAnalyzer.NetCore/Augurk.CSharpAnalyzer.NetCore.csproj /verbosity:minimal /t:Restore,Publish /p:RuntimeIdentifier=linux-x64 /p:Configuration=%CONFIGURATION% /p:Version=%GITVERSION_MAJORMINORPATCH% /p:InformationalVersion=%GITVERSION_INFORMATIONALVERSION%
- cmd: msbuild Augurk.CSharpAnalyzer.NetCore/Augurk.CSharpAnalyzer.NetCore.csproj /verbosity:minimal /t:Restore,Publish /p:RuntimeIdentifier=osx-x64 /p:Configuration=%CONFIGURATION% /p:Version=%GITVERSION_MAJORMINORPATCH% /p:InformationalVersion=%GITVERSION_INFORMATIONALVERSION%
- cmd: msbuild Augurk.CSharpAnalyzer.NetFx/Augurk.CSharpAnalyzer.NetFx.csproj /verbosity:minimal /t:Restore,Build /p:Configuration=%CONFIGURATION% /p:Version=%GITVERSION_MAJORMINORPATCH% /p:InformationalVersion=%GITVERSION_INFORMATIONALVERSION%
- cmd: ECHO nuget pack Augurk.CSharpAnalyzer.nuspec -version "%GitVersion_NuGetVersion%" -prop "Configuration=%CONFIGURATION%"
- cmd: nuget pack Augurk.CSharpAnalyzer.nuspec -version "%GitVersion_NuGetVersion%" -prop "Configuration=%CONFIGURATION%"
- cmd: appveyor PushArtifact "Augurk.CSharpAnalyzer.%GitVersion_NuGetVersion%.nupkg"